/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sensor;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import org.eclipse.paho.client.mqttv3.MqttException;

/**
 *
 * @author Kelwin
 */
public class Sensor extends javax.swing.JFrame {

    /**
     * Creates new form Environment
     */
    public Sensor() {

        initComponents();
        temp.setText("" + temperature + " °C");
        hum.setText("" + humidity + " %");
        ele.setText("" + electricity + " Kwh");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sliderTemp = new javax.swing.JSlider();
        temp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lightLR1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lightLR2 = new javax.swing.JToggleButton();
        lightLR3 = new javax.swing.JToggleButton();
        windowLR1 = new javax.swing.JToggleButton();
        windowLR2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtPeopleLR = new javax.swing.JTextField();
        btnLR = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        windowLR3 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LightSR1 = new javax.swing.JToggleButton();
        LightSR2 = new javax.swing.JToggleButton();
        windowSR1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtPeopleSR = new javax.swing.JTextField();
        btnSR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lightBR1 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        windowBR1 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        txtPeopleBR = new javax.swing.JTextField();
        btnBR = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lightKT1 = new javax.swing.JToggleButton();
        lightKT2 = new javax.swing.JToggleButton();
        windowKT1 = new javax.swing.JToggleButton();
        windowKT2 = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        txtPeopleKT = new javax.swing.JTextField();
        btnKT = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        hum = new javax.swing.JTextField();
        sliderHum = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();
        ele = new javax.swing.JTextField();
        sliderEle = new javax.swing.JSlider();
        labelLights = new javax.swing.JLabel();
        labelWindows = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Environment ");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Temperature (°C):");

        sliderTemp.setMajorTickSpacing(2);
        sliderTemp.setMaximum(30);
        sliderTemp.setMinimum(-10);
        sliderTemp.setMinorTickSpacing(1);
        sliderTemp.setPaintLabels(true);
        sliderTemp.setPaintTicks(true);
        sliderTemp.setSnapToTicks(true);
        sliderTemp.setValue(0);
        sliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTempStateChanged(evt);
            }
        });

        temp.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "LivingRoom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lightLR1.setText("OFF");
        lightLR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightLR1ItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Light-1:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Light-2:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Light-3:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Window-1:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Window-2:");

        lightLR2.setText("OFF");
        lightLR2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightLR2ItemStateChanged(evt);
            }
        });

        lightLR3.setText("OFF");
        lightLR3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightLR3ItemStateChanged(evt);
            }
        });

        windowLR1.setText("CLOSED");
        windowLR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowLR1ItemStateChanged(evt);
            }
        });

        windowLR2.setText("CLOSED");
        windowLR2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowLR2ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("People-In:");

        txtPeopleLR.setText("0");

        btnLR.setText("Confirm");
        btnLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLRActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Window-3");

        windowLR3.setText("CLOSED");
        windowLR3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowLR3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lightLR1))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lightLR2))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lightLR3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel7))
                                                .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(windowLR3)
                                                .addComponent(windowLR1)
                                                .addComponent(windowLR2))
                                        .addGap(27, 27, 27))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPeopleLR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLR)
                                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lightLR1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(windowLR1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(lightLR2)
                                .addComponent(jLabel8)
                                .addComponent(windowLR2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(lightLR3)
                                .addComponent(jLabel12)
                                .addComponent(windowLR3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtPeopleLR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLR))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "SleepingRoom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Light-1:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Light-2:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Window-1:");

        LightSR1.setText("OFF");
        LightSR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LightSR1ItemStateChanged(evt);
            }
        });

        LightSR2.setText("OFF");
        LightSR2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LightSR2ItemStateChanged(evt);
            }
        });

        windowSR1.setText("CLOSED");
        windowSR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowSR1ItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("People-In:");

        txtPeopleSR.setText("0");

        btnSR.setText("Confirm");
        btnSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                        .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(LightSR1)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(windowSR1)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LightSR2)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtPeopleSR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnSR)))
                                        .addContainerGap(89, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(LightSR1)
                                .addComponent(windowSR1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(LightSR2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtPeopleSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSR))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "BathRoom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Light-1:");

        lightBR1.setText("OFF");
        lightBR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightBR1ItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Window-1:");

        windowBR1.setText("CLOSED");
        windowBR1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowBR1ItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("People-In:");

        txtPeopleBR.setText("0");

        btnBR.setText("Confirm");
        btnBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(30, 30, 30)
                                        .addComponent(lightBR1))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(windowBR1))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPeopleBR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBR)))
                        .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(lightBR1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(windowBR1)
                                .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtPeopleBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBR))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Kitchen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Light-1:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Light-2:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Window-1:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Window-2:");

        lightKT1.setText("OFF");
        lightKT1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightKT1ItemStateChanged(evt);
            }
        });

        lightKT2.setText("OFF");
        lightKT2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lightKT2ItemStateChanged(evt);
            }
        });

        windowKT1.setText("CLOSED");
        windowKT1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowKT1ItemStateChanged(evt);
            }
        });

        windowKT2.setText("CLOSED");
        windowKT2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowKT2ItemStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("People-In:");

        txtPeopleKT.setText("0");

        btnKT.setText("Confirm");
        btnKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(lightKT1))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(lightKT2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel18)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(windowKT1))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(windowKT2))))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPeopleKT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnKT)))
                        .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(lightKT1)
                                .addComponent(jLabel18)
                                .addComponent(windowKT1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(windowKT2))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(lightKT2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(txtPeopleKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKT))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Humidity (%):");

        hum.setEnabled(false);

        sliderHum.setMajorTickSpacing(5);
        sliderHum.setMinorTickSpacing(5);
        sliderHum.setPaintLabels(true);
        sliderHum.setPaintTicks(true);
        sliderHum.setSnapToTicks(true);
        sliderHum.setToolTipText("");
        sliderHum.setValue(5);
        sliderHum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHumStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Electricity (Kwh):");

        ele.setEnabled(false);

        sliderEle.setMajorTickSpacing(100);
        sliderEle.setMaximum(1000);
        sliderEle.setMinorTickSpacing(50);
        sliderEle.setPaintLabels(true);
        sliderEle.setPaintTicks(true);
        sliderEle.setSnapToTicks(true);
        sliderEle.setValue(0);
        sliderEle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderEleStateChanged(evt);
            }
        });

        labelLights.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLights.setText("Lights On: 0/8");

        labelWindows.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelWindows.setText("Windows Open: 0/7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelLights)
                                                .addComponent(labelWindows)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ele, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(sliderTemp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sliderHum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sliderEle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(hum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                        .addGap(6, 6, 6)
                        .addComponent(sliderHum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(ele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(sliderEle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(labelLights)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelWindows)
                                        .addGap(95, 95, 95))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTempStateChanged

        temperature = sliderTemp.getValue();
        temp.setText("" + temperature + " °C");

        publishData();
    }//GEN-LAST:event_sliderTempStateChanged

    private void lightLR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightLR1ItemStateChanged
        if (lightLR1.isSelected()) {
            LivingRoom_Lights_l1 = "ON";
            lightLR1.setText("ON");
            lightLR1.setBackground(Color.YELLOW);
            Lights_LivingRoom++;
        } else {
            LivingRoom_Lights_l1 = "OFF";
            lightLR1.setText("OFF");
            lightLR1.setBackground(Color.GRAY);
            Lights_LivingRoom--;
        }
        //System.out.println(Lights_LivingRoom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightLR1ItemStateChanged

    private void lightLR2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightLR2ItemStateChanged
        if (lightLR2.isSelected()) {
            LivingRoom_Lights_l2 = "ON";
            lightLR2.setText("ON");
            lightLR2.setBackground(Color.YELLOW);
            Lights_LivingRoom++;
        } else {
            LivingRoom_Lights_l2 = "OFF";
            lightLR2.setText("OFF");
            lightLR2.setBackground(Color.GRAY);
            Lights_LivingRoom--;
        }
        //System.out.println(Lights_LivingRoom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightLR2ItemStateChanged

    private void lightLR3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightLR3ItemStateChanged

        if (lightLR3.isSelected()) {
            LivingRoom_Lights_l3 = "ON";
            lightLR3.setText("ON");
            lightLR3.setBackground(Color.YELLOW);
            Lights_LivingRoom++;
        } else {
            LivingRoom_Lights_l3 = "OFF";
            lightLR3.setText("OFF");
            lightLR3.setBackground(Color.GRAY);
            Lights_LivingRoom--;
        }
        //System.out.println(Lights_LivingRoom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightLR3ItemStateChanged

    private void windowLR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowLR1ItemStateChanged
        if (windowLR1.isSelected()) {
            LivingRoom_Windows_l1 = "ON";
            windowLR1.setText("OPEN");
            windowLR1.setBackground(Color.GREEN);
            Windows_LivingRoom++;
        } else {
            LivingRoom_Windows_l1 = "OFF";
            windowLR1.setText("CLOSED");
            windowLR1.setBackground(Color.GRAY);
            Windows_LivingRoom--;
        }
        //System.out.println(Windows_LivingRoom);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowLR1ItemStateChanged

    private void windowLR2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowLR2ItemStateChanged
        if (windowLR2.isSelected()) {
            LivingRoom_Windows_l2 = "ON";
            windowLR2.setText("OPEN");
            windowLR2.setBackground(Color.GREEN);
            Windows_LivingRoom++;
        } else {
            LivingRoom_Windows_l2 = "OFF";
            windowLR2.setText("CLOSED");
            windowLR2.setBackground(Color.GRAY);
            Windows_LivingRoom--;
        }
        //System.out.println(Windows_LivingRoom);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowLR2ItemStateChanged

    private void LightSR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LightSR1ItemStateChanged
        if (LightSR1.isSelected()) {
            SleepingRoom_Lights_l1 = "ON";
            LightSR1.setText("ON");
            LightSR1.setBackground(Color.YELLOW);
            Lights_SleepingRoom++;
        } else {
            SleepingRoom_Lights_l1 = "OFF";
            LightSR1.setText("OFF");
            LightSR1.setBackground(Color.GRAY);
            Lights_SleepingRoom--;
        }
        //System.out.println(Lights_SleepingRoom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_LightSR1ItemStateChanged

    private void LightSR2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LightSR2ItemStateChanged
        if (LightSR2.isSelected()) {
            SleepingRoom_Lights_l2 = "ON";
            LightSR2.setText("ON");
            LightSR2.setBackground(Color.YELLOW);
            Lights_SleepingRoom++;
        } else {
            SleepingRoom_Lights_l2 = "OFF";
            LightSR2.setText("OFF");
            LightSR2.setBackground(Color.GRAY);
            Lights_SleepingRoom--;
        }
        //System.out.println(Lights_SleepingRoom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_LightSR2ItemStateChanged

    private void windowSR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowSR1ItemStateChanged
        if (windowSR1.isSelected()) {
            SleepingRoom_Windows_l1 = "ON";
            windowSR1.setText("OPEN");
            windowSR1.setBackground(Color.GREEN);
            Windows_SleepingRoom++;
        } else {
            SleepingRoom_Windows_l1 = "OFF";
            windowSR1.setText("CLOSED");
            windowSR1.setBackground(Color.GRAY);
            Windows_SleepingRoom--;
        }
        //System.out.println(Windows_SleepingRoom);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowSR1ItemStateChanged

    private void lightBR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightBR1ItemStateChanged
        if (lightBR1.isSelected()) {
            Bathroom_Lights_l1 = "ON";
            lightBR1.setText("ON");
            lightBR1.setBackground(Color.YELLOW);
            Lights_Bathroom++;
        } else {
            Bathroom_Lights_l1 = "OFF";
            lightBR1.setText("OFF");
            lightBR1.setBackground(Color.GRAY);
            Lights_Bathroom--;
        }
        //System.out.println(Lights_Bathroom);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightBR1ItemStateChanged

    private void windowBR1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowBR1ItemStateChanged
        if (windowBR1.isSelected()) {
            Bathroom_Windows_l1 = "ON";
            windowBR1.setText("OPEN");
            windowBR1.setBackground(Color.GREEN);
            Windows_Bathroom++;
        } else {
            Bathroom_Windows_l1 = "OFF";
            windowBR1.setText("CLOSED");
            windowBR1.setBackground(Color.GRAY);
            Windows_Bathroom--;
        }
        //System.out.println(Windows_Bathroom);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowBR1ItemStateChanged

    private void lightKT1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightKT1ItemStateChanged
        if (lightKT1.isSelected()) {
            Kitchen_Lights_l1 = "ON";
            lightKT1.setText("ON");
            lightKT1.setBackground(Color.YELLOW);
            Lights_Kitchen++;
        } else {
            Kitchen_Lights_l1 = "OFF";
            lightKT1.setText("OFF");
            lightKT1.setBackground(Color.GRAY);
            Lights_Kitchen--;
        }
        //System.out.println(Lights_Kitchen);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightKT1ItemStateChanged

    private void lightKT2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lightKT2ItemStateChanged
        if (lightKT2.isSelected()) {
            Kitchen_Lights_l2 = "ON";
            lightKT2.setText("ON");
            lightKT2.setBackground(Color.YELLOW);
            Lights_Kitchen++;
        } else {
            Kitchen_Lights_l2 = "OFF";
            lightKT2.setText("OFF");
            lightKT2.setBackground(Color.GRAY);
            Lights_Kitchen--;
        }
        //System.out.println(Lights_Kitchen);
        LightsOn = Lights_LivingRoom + Lights_Kitchen + Lights_SleepingRoom + Lights_Bathroom;
        labelLights.setText("Light On: " + LightsOn + "/8");
        publishData();
    }//GEN-LAST:event_lightKT2ItemStateChanged

    private void windowKT1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowKT1ItemStateChanged
        if (windowKT1.isSelected()) {
            Kitchen_Windows_l1 = "ON";
            windowKT1.setText("OPEN");
            windowKT1.setBackground(Color.GREEN);
            Windows_Kitchen++;
        } else {
            Kitchen_Windows_l1 = "OFF";
            windowKT1.setText("CLOSED");
            windowKT1.setBackground(Color.GRAY);
            Windows_Kitchen--;
        }
        //System.out.println(Windows_Kitchen);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowKT1ItemStateChanged

    private void windowKT2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowKT2ItemStateChanged
        if (windowKT2.isSelected()) {
            Kitchen_Windows_l2 = "ON";
            windowKT2.setText("OPEN");
            windowKT2.setBackground(Color.GREEN);
            Windows_Kitchen++;
        } else {
            Kitchen_Windows_l2 = "OFF";
            windowKT2.setText("CLOSED");
            windowKT2.setBackground(Color.GRAY);
            Windows_Kitchen--;
        }
        //System.out.println(Windows_Kitchen);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowKT2ItemStateChanged

    private void btnLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLRActionPerformed
        LivingRoom_People = Integer.parseInt(txtPeopleLR.getText());
        //System.out.println(LivingRoom_People);
        publishData();

    }//GEN-LAST:event_btnLRActionPerformed

    private void btnSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSRActionPerformed
        SleepingRoom_People = Integer.parseInt(txtPeopleSR.getText());
        //System.out.println(SleepingRoom_People);
        publishData();
    }//GEN-LAST:event_btnSRActionPerformed

    private void btnBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRActionPerformed
        Bathroom_People = Integer.parseInt(txtPeopleBR.getText());
        //System.out.println(Bathroom_People);
        publishData();
    }//GEN-LAST:event_btnBRActionPerformed

    private void btnKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKTActionPerformed
        Kitchen_People = Integer.parseInt(txtPeopleKT.getText());
        //System.out.println(Kitchen_People);
        publishData();
    }//GEN-LAST:event_btnKTActionPerformed

    private void windowLR3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowLR3ItemStateChanged
        if (windowLR3.isSelected()) {
            LivingRoom_Windows_l3 = "ON";
            windowLR3.setText("OPEN");
            windowLR3.setBackground(Color.GREEN);
            Windows_LivingRoom++;
        } else {
            LivingRoom_Windows_l3 = "OFF";
            windowLR3.setText("CLOSED");
            windowLR3.setBackground(Color.GRAY);
            Windows_LivingRoom--;
        }
        //System.out.println(Windows_LivingRoom);
        Windows_Number = Windows_LivingRoom + Windows_Kitchen + Windows_SleepingRoom + Windows_Bathroom;
        labelWindows.setText("Windows Open: " + Windows_Number + "/7");
        publishData();
    }//GEN-LAST:event_windowLR3ItemStateChanged

    private void sliderHumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHumStateChanged
        humidity = sliderHum.getValue();
        hum.setText("" + humidity + " %");
        publishData();
    }//GEN-LAST:event_sliderHumStateChanged

    private void sliderEleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderEleStateChanged
        electricity = sliderEle.getValue();
        ele.setText("" + electricity + " Kwh");
        publishData();

    }//GEN-LAST:event_sliderEleStateChanged

    @SuppressWarnings("empty-statement")
    public static void main(String args[]) throws InterruptedException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        final Sensor k = new Sensor();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                k.setVisible(true);
            }
        });
        k.publishData();
        //for(;;){
        //Thread.sleep(4000);
        try {
			PahoMsgArrived p = new PahoMsgArrived(k);
		} catch (MqttException e) {
			JOptionPane.showMessageDialog(null, "MQTT exception in Sensor.java. However, program will not stop", "MQTT exception", JOptionPane.INFORMATION_MESSAGE);
			e.printStackTrace();
		}
        //while (true);

        //}
    }

    public void publishData() {
        Paho p = null;
        try {
            p = new Paho();
        } catch (MqttException ex) {
            Logger.getLogger(Sensor.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("Seding with MQTT each 10 seconds..");

        //Send updates
        p.send("home/general/electricity", sliderEle.getValue() + "");
        p.send("home/general/humidity", sliderHum.getValue() + "");
        p.send("home/general/temperature", sliderTemp.getValue() + "");

        p.send("home/general/lights", LightsOn + "");
        p.send("home/livingroom/lights", Lights_LivingRoom + "");
        p.send("home/kitchen/lights", Lights_Kitchen + "");
        p.send("home/sleepingroom/lights", Lights_SleepingRoom + "");
        p.send("home/bathroom/lights", Lights_Bathroom + "");
        p.send("home/livingroom/lights/1", LivingRoom_Lights_l1 + "");
        p.send("home/livingroom/lights/2", LivingRoom_Lights_l2 + "");
        p.send("home/livingroom/lights/3", LivingRoom_Lights_l3 + "");
        p.send("home/kitchen/lights/1", Kitchen_Lights_l1 + "");
        p.send("home/kitchen/lights/2", Kitchen_Lights_l2 + "");
        p.send("home/sleepingroom/lights/1", SleepingRoom_Lights_l1 + "");
        p.send("home/sleepingroom/lights/2", SleepingRoom_Lights_l2 + "");
        p.send("home/bathroom/lights/1", Bathroom_Lights_l1 + "");

        p.send("home/general/windows", Windows_Number + "");
        p.send("home/livingroom/windows", Windows_LivingRoom + "");
        p.send("home/kitchen/windows", Windows_Kitchen + "");
        p.send("home/sleepingroom/windows", Windows_SleepingRoom + "");
        p.send("home/bathroom/windows", Windows_Bathroom + "");
        p.send("home/livingroom/windows/1", LivingRoom_Windows_l1 + "");
        p.send("home/livingroom/windows/2", LivingRoom_Windows_l2 + "");
        p.send("home/livingroom/windows/3", LivingRoom_Windows_l3 + "");
        p.send("home/kitchen/windows/1", Kitchen_Windows_l1 + "");
        p.send("home/kitchen/windows/2", Kitchen_Windows_l2 + "");
        p.send("home/sleepingroom/windows/1", SleepingRoom_Windows_l1 + "");
        p.send("home/bathroom/windows/1", Bathroom_Windows_l1 + "");

        p.send("home/livingroom/people", LivingRoom_People + "");
        p.send("home/kitchen/people", Kitchen_People + "");
        p.send("home/sleepingroom/people", SleepingRoom_People + "");
        p.send("home/bathroom/people", Bathroom_People + "");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LightSR1;
    private javax.swing.JToggleButton LightSR2;
    private javax.swing.JButton btnBR;
    private javax.swing.JButton btnKT;
    private javax.swing.JButton btnLR;
    private javax.swing.JButton btnSR;
    private javax.swing.JTextField ele;
    private javax.swing.JTextField hum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelLights;
    private javax.swing.JLabel labelWindows;
    private javax.swing.JToggleButton lightBR1;
    private javax.swing.JToggleButton lightKT1;
    private javax.swing.JToggleButton lightKT2;
    private javax.swing.JToggleButton lightLR1;
    private javax.swing.JToggleButton lightLR2;
    private javax.swing.JToggleButton lightLR3;
    private javax.swing.JSlider sliderEle;
    private javax.swing.JSlider sliderHum;
    private javax.swing.JSlider sliderTemp;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField txtPeopleBR;
    private javax.swing.JTextField txtPeopleKT;
    private javax.swing.JTextField txtPeopleLR;
    private javax.swing.JTextField txtPeopleSR;
    private javax.swing.JToggleButton windowBR1;
    private javax.swing.JToggleButton windowKT1;
    private javax.swing.JToggleButton windowKT2;
    private javax.swing.JToggleButton windowLR1;
    private javax.swing.JToggleButton windowLR2;
    private javax.swing.JToggleButton windowLR3;
    private javax.swing.JToggleButton windowSR1;
    // End of variables declaration//GEN-END:variables

    int temperature = 0;
    int humidity = 5;
    int electricity = 0;

    int LightsOn = 0, Lights_LivingRoom = 0, Lights_Kitchen = 0, Lights_SleepingRoom = 0, Lights_Bathroom = 0;
    String LivingRoom_Lights_l1 = "OFF", LivingRoom_Lights_l2 = "OFF", LivingRoom_Lights_l3 = "OFF", Kitchen_Lights_l1 = "OFF";
    String Kitchen_Lights_l2 = "OFF", SleepingRoom_Lights_l1 = "OFF", SleepingRoom_Lights_l2 = "OFF", Bathroom_Lights_l1 = "OFF";
    int Windows_Number = 0, Windows_LivingRoom = 0, Windows_Kitchen = 0, Windows_SleepingRoom = 0, Windows_Bathroom = 0;
    int LivingRoom_People = 0, Kitchen_People = 0, SleepingRoom_People = 0, Bathroom_People = 0;
    String LivingRoom_Windows_l1 = "OFF", LivingRoom_Windows_l2 = "OFF", LivingRoom_Windows_l3 = "OFF", Kitchen_Windows_l1 = "OFF", Kitchen_Windows_l2 = "OFF";
    String SleepingRoom_Windows_l1 = "OFF", Bathroom_Windows_l1 = "OFF";

    public JToggleButton getLightSR1() {
        return LightSR1;
    }

    public void setLightSR1(JToggleButton LightSR1) {
        this.LightSR1 = LightSR1;
    }

    public JToggleButton getLightSR2() {
        return LightSR2;
    }

    public void setLightSR2(JToggleButton LightSR2) {
        this.LightSR2 = LightSR2;
    }

    public JButton getBtnBR() {
        return btnBR;
    }

    public void setBtnBR(JButton btnBR) {
        this.btnBR = btnBR;
    }

    public JButton getBtnKT() {
        return btnKT;
    }

    public void setBtnKT(JButton btnKT) {
        this.btnKT = btnKT;
    }

    public JButton getBtnLR() {
        return btnLR;
    }

    public void setBtnLR(JButton btnLR) {
        this.btnLR = btnLR;
    }

    public JButton getBtnSR() {
        return btnSR;
    }

    public void setBtnSR(JButton btnSR) {
        this.btnSR = btnSR;
    }

    public JTextField getEle() {
        return ele;
    }

    public void setEle(JTextField ele) {
        this.ele = ele;
    }

    public JTextField getHum() {
        return hum;
    }

    public void setHum(JTextField hum) {
        this.hum = hum;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JLabel getLabelLights() {
        return labelLights;
    }

    public void setLabelLights(JLabel labelLights) {
        this.labelLights = labelLights;
    }

    public JLabel getLabelWindows() {
        return labelWindows;
    }

    public void setLabelWindows(JLabel labelWindows) {
        this.labelWindows = labelWindows;
    }

    public JToggleButton getLightBR1() {
        return lightBR1;
    }

    public void setLightBR1(JToggleButton lightBR1) {
        this.lightBR1 = lightBR1;
    }

    public JToggleButton getLightKT1() {
        return lightKT1;
    }

    public void setLightKT1(JToggleButton lightKT1) {
        this.lightKT1 = lightKT1;
    }

    public JToggleButton getLightKT2() {
        return lightKT2;
    }

    public void setLightKT2(JToggleButton lightKT2) {
        this.lightKT2 = lightKT2;
    }

    public JToggleButton getLightLR1() {
        return lightLR1;
    }

    public void setLightLR1(JToggleButton lightLR1) {
        this.lightLR1 = lightLR1;
    }

    public JToggleButton getLightLR2() {
        return lightLR2;
    }

    public void setLightLR2(JToggleButton lightLR2) {
        this.lightLR2 = lightLR2;
    }

    public JToggleButton getLightLR3() {
        return lightLR3;
    }

    public void setLightLR3(JToggleButton lightLR3) {
        this.lightLR3 = lightLR3;
    }

    public JSlider getSliderEle() {
        return sliderEle;
    }

    public void setSliderEle(JSlider sliderEle) {
        this.sliderEle = sliderEle;
    }

    public JSlider getSliderHum() {
        return sliderHum;
    }

    public void setSliderHum(JSlider sliderHum) {
        this.sliderHum = sliderHum;
    }

    public JSlider getSliderTemp() {
        return sliderTemp;
    }

    public void setSliderTemp(JSlider sliderTemp) {
        this.sliderTemp = sliderTemp;
    }

    public JTextField getTemp() {
        return temp;
    }

    public void setTemp(JTextField temp) {
        this.temp = temp;
    }

    public JTextField getTxtPeopleBR() {
        return txtPeopleBR;
    }

    public void setTxtPeopleBR(JTextField txtPeopleBR) {
        this.txtPeopleBR = txtPeopleBR;
    }

    public JTextField getTxtPeopleKT() {
        return txtPeopleKT;
    }

    public void setTxtPeopleKT(JTextField txtPeopleKT) {
        this.txtPeopleKT = txtPeopleKT;
    }

    public JTextField getTxtPeopleLR() {
        return txtPeopleLR;
    }

    public void setTxtPeopleLR(JTextField txtPeopleLR) {
        this.txtPeopleLR = txtPeopleLR;
    }

    public JTextField getTxtPeopleSR() {
        return txtPeopleSR;
    }

    public void setTxtPeopleSR(JTextField txtPeopleSR) {
        this.txtPeopleSR = txtPeopleSR;
    }

    public JToggleButton getWindowBR1() {
        return windowBR1;
    }

    public void setWindowBR1(JToggleButton windowBR1) {
        this.windowBR1 = windowBR1;
    }

    public JToggleButton getWindowKT1() {
        return windowKT1;
    }

    public void setWindowKT1(JToggleButton windowKT1) {
        this.windowKT1 = windowKT1;
    }

    public JToggleButton getWindowKT2() {
        return windowKT2;
    }

    public void setWindowKT2(JToggleButton windowKT2) {
        this.windowKT2 = windowKT2;
    }

    public JToggleButton getWindowLR1() {
        return windowLR1;
    }

    public void setWindowLR1(JToggleButton windowLR1) {
        this.windowLR1 = windowLR1;
    }

    public JToggleButton getWindowLR2() {
        return windowLR2;
    }

    public void setWindowLR2(JToggleButton windowLR2) {
        this.windowLR2 = windowLR2;
    }

    public JToggleButton getWindowLR3() {
        return windowLR3;
    }

    public void setWindowLR3(JToggleButton windowLR3) {
        this.windowLR3 = windowLR3;
    }

    public JToggleButton getWindowSR1() {
        return windowSR1;
    }

    public void setWindowSR1(JToggleButton windowSR1) {
        this.windowSR1 = windowSR1;
    }

    public int getTemperature() {
        return temperature;
    }

    public void setTemperature(int temperature) {
        this.temperature = temperature;
    }

    public int getHumidity() {
        return humidity;
    }

    public void setHumidity(int humidity) {
        this.humidity = humidity;
    }

    public int getElectricity() {
        return electricity;
    }

    public void setElectricity(int electricity) {
        this.electricity = electricity;
    }

    public int getLightsOn() {
        return LightsOn;
    }

    public void setLightsOn(int LightsOn) {
        this.LightsOn = LightsOn;
    }

    public int getLights_LivingRoom() {
        return Lights_LivingRoom;
    }

    public void setLights_LivingRoom(int Lights_LivingRoom) {
        this.Lights_LivingRoom = Lights_LivingRoom;
    }

    public int getLights_Kitchen() {
        return Lights_Kitchen;
    }

    public void setLights_Kitchen(int Lights_Kitchen) {
        this.Lights_Kitchen = Lights_Kitchen;
    }

    public int getLights_SleepingRoom() {
        return Lights_SleepingRoom;
    }

    public void setLights_SleepingRoom(int Lights_SleepingRoom) {
        this.Lights_SleepingRoom = Lights_SleepingRoom;
    }

    public int getLights_Bathroom() {
        return Lights_Bathroom;
    }

    public void setLights_Bathroom(int Lights_Bathroom) {
        this.Lights_Bathroom = Lights_Bathroom;
    }

    public String getLivingRoom_Lights_l1() {
        return LivingRoom_Lights_l1;
    }

    public void setLivingRoom_Lights_l1(String LivingRoom_Lights_l1) {
        this.LivingRoom_Lights_l1 = LivingRoom_Lights_l1;
    }

    public String getLivingRoom_Lights_l2() {
        return LivingRoom_Lights_l2;
    }

    public void setLivingRoom_Lights_l2(String LivingRoom_Lights_l2) {
        this.LivingRoom_Lights_l2 = LivingRoom_Lights_l2;
    }

    public String getLivingRoom_Lights_l3() {
        return LivingRoom_Lights_l3;
    }

    public void setLivingRoom_Lights_l3(String LivingRoom_Lights_l3) {
        this.LivingRoom_Lights_l3 = LivingRoom_Lights_l3;
    }

    public String getKitchen_Lights_l1() {
        return Kitchen_Lights_l1;
    }

    public void setKitchen_Lights_l1(String Kitchen_Lights_l1) {
        this.Kitchen_Lights_l1 = Kitchen_Lights_l1;
    }

    public String getKitchen_Lights_l2() {
        return Kitchen_Lights_l2;
    }

    public void setKitchen_Lights_l2(String Kitchen_Lights_l2) {
        this.Kitchen_Lights_l2 = Kitchen_Lights_l2;
    }

    public String getSleepingRoom_Lights_l1() {
        return SleepingRoom_Lights_l1;
    }

    public void setSleepingRoom_Lights_l1(String SleepingRoom_Lights_l1) {
        this.SleepingRoom_Lights_l1 = SleepingRoom_Lights_l1;
    }

    public String getSleepingRoom_Lights_l2() {
        return SleepingRoom_Lights_l2;
    }

    public void setSleepingRoom_Lights_l2(String SleepingRoom_Lights_l2) {
        this.SleepingRoom_Lights_l2 = SleepingRoom_Lights_l2;
    }

    public String getBathroom_Lights_l1() {
        return Bathroom_Lights_l1;
    }

    public void setBathroom_Lights_l1(String Bathroom_Lights_l1) {
        this.Bathroom_Lights_l1 = Bathroom_Lights_l1;
    }

    public int getWindows_Number() {
        return Windows_Number;
    }

    public void setWindows_Number(int Windows_Number) {
        this.Windows_Number = Windows_Number;
    }

    public int getWindows_LivingRoom() {
        return Windows_LivingRoom;
    }

    public void setWindows_LivingRoom(int Windows_LivingRoom) {
        this.Windows_LivingRoom = Windows_LivingRoom;
    }

    public int getWindows_Kitchen() {
        return Windows_Kitchen;
    }

    public void setWindows_Kitchen(int Windows_Kitchen) {
        this.Windows_Kitchen = Windows_Kitchen;
    }

    public int getWindows_SleepingRoom() {
        return Windows_SleepingRoom;
    }

    public void setWindows_SleepingRoom(int Windows_SleepingRoom) {
        this.Windows_SleepingRoom = Windows_SleepingRoom;
    }

    public int getWindows_Bathroom() {
        return Windows_Bathroom;
    }

    public void setWindows_Bathroom(int Windows_Bathroom) {
        this.Windows_Bathroom = Windows_Bathroom;
    }

    public int getLivingRoom_People() {
        return LivingRoom_People;
    }

    public void setLivingRoom_People(int LivingRoom_People) {
        this.LivingRoom_People = LivingRoom_People;
    }

    public int getKitchen_People() {
        return Kitchen_People;
    }

    public void setKitchen_People(int Kitchen_People) {
        this.Kitchen_People = Kitchen_People;
    }

    public int getSleepingRoom_People() {
        return SleepingRoom_People;
    }

    public void setSleepingRoom_People(int SleepingRoom_People) {
        this.SleepingRoom_People = SleepingRoom_People;
    }

    public int getBathroom_People() {
        return Bathroom_People;
    }

    public void setBathroom_People(int Bathroom_People) {
        this.Bathroom_People = Bathroom_People;
    }

    public String getLivingRoom_Windows_l1() {
        return LivingRoom_Windows_l1;
    }

    public void setLivingRoom_Windows_l1(String LivingRoom_Windows_l1) {
        this.LivingRoom_Windows_l1 = LivingRoom_Windows_l1;
    }

    public String getLivingRoom_Windows_l2() {
        return LivingRoom_Windows_l2;
    }

    public void setLivingRoom_Windows_l2(String LivingRoom_Windows_l2) {
        this.LivingRoom_Windows_l2 = LivingRoom_Windows_l2;
    }

    public String getLivingRoom_Windows_l3() {
        return LivingRoom_Windows_l3;
    }

    public void setLivingRoom_Windows_l3(String LivingRoom_Windows_l3) {
        this.LivingRoom_Windows_l3 = LivingRoom_Windows_l3;
    }

    public String getKitchen_Windows_l1() {
        return Kitchen_Windows_l1;
    }

    public void setKitchen_Windows_l1(String Kitchen_Windows_l1) {
        this.Kitchen_Windows_l1 = Kitchen_Windows_l1;
    }

    public String getKitchen_Windows_l2() {
        return Kitchen_Windows_l2;
    }

    public void setKitchen_Windows_l2(String Kitchen_Windows_l2) {
        this.Kitchen_Windows_l2 = Kitchen_Windows_l2;
    }

    public String getSleepingRoom_Windows_l1() {
        return SleepingRoom_Windows_l1;
    }

    public void setSleepingRoom_Windows_l1(String SleepingRoom_Windows_l1) {
        this.SleepingRoom_Windows_l1 = SleepingRoom_Windows_l1;
    }

    public String getBathroom_Windows_l1() {
        return Bathroom_Windows_l1;
    }

    public void setBathroom_Windows_l1(String Bathroom_Windows_l1) {
        this.Bathroom_Windows_l1 = Bathroom_Windows_l1;
    }
}
